# Generated by Django 2.1.7 on 2019-04-18 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.Document')),
                ('location', models.CharField(max_length=4096)),
                ('attachment', models.TextField(blank=True, null=True)),
                ('sent_date', models.DateTimeField()),
                ('from_email_address', models.CharField(max_length=4096)),
                ('to', models.TextField()),
                ('cc', models.TextField(blank=True, null=True)),
                ('bcc', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(max_length=4096)),
                ('body_txt', models.TextField(blank=True, null=True)),
                ('body_html', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('server.document',),
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='document',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_server.document_set+', to='contenttypes.ContentType'),
        ),
    ]
