# Generated by Django 2.1.7 on 2019-04-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190418_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='document_type',
            field=models.CharField(choices=[('text', 'text document'), ('email', 'email')], default='text', max_length=30),
        ),
    ]
